### ISSUE TITLE
Raid Markers not showing up after new update

### ISSUE THREAD

**Issue by RobotNinjaa** [cr4ckp0t/ElvUI_RaidMarkers#8] opened 2020-10-14 19:54 UTC
Elvui Ver. 12.00
Elvui Raid markers Ver. 6.00
Recently updated both of these and the raid marker addon still isnt showing up

**Comment by rhainstorm** [comment] 2020-10-15 22:58
same for me and throws lua errors in elvui so i had to disable it untill fixed

**Comment by cr4ckp0t** [comment] 2020-10-16 03:26
While I already know what the issue is, just for future tickets you open please try to copy the error message. Just saying "it doesn't work" does not tell me figure out what's going on.

In this case it's not a big deal since I know what it is. I am fixing it now.

**Comment by cr4ckp0t** [comment] 2020-10-16 04:05
Fixed in 6.0.1 just pushed to GitHub.

**Closed as completed by cr4ckp0t** 2020-10-16 04:05 UTC
